---
## You can override the default chart name (i.e., .Charts.name) when desired using the following parameter.
## This is the only way to have more than one deployment of this
nameOverride: null

## Number of Hive Metastore instances.
## Following the documentation, given Hive Metastore is stateless we could have more than one instance.
## https://cwiki.apache.org/confluence/display/Hive/AdminManual+Metastore+Administration
replicaCount: 1

## Default Hive image and tag. Please build image locally before applying this.
image:
  name: hive-metastore
  tag: latest
  pullPolicy: IfNotPresent

env:
  HIVE_DB_EXTERNAL: "true"
  HIVE_DB_HOST: "rts-generic-job-poc-db.ctq4vela0pmd.us-west-2.rds.amazonaws.com:3306"
  HIVE_DB_NAME: hive_metastore_db
  HIVE_DB_USER: root
  HIVE_DB_PASS: gfqv1p7198s9wg0emgdb3t2w06rl6tig
  HIVE_CONF_PARAMS: hive.metastore.event.db.notification.api.auth:false;hadoop.proxyuser.hive.hosts:HS2_HOST;hadoop.proxyuser.hive.groups:*;datanucleus.autoStartMechanism:SchemaTable

## Resource requests and limits: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi

service:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP

## Auto-scaling (hpa) configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90
  targetMemoryUtilizationPercentage: 90