{{- if eq .Values.env.HIVE_DB_EXTERNAL "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-metastore.name" . }}-conf-templates
  labels:
    {{- include "hive-metastore.labels" $ | trim | nindent 4 }}
data:
  {{- (tpl (.Files.Glob "configsets/*" ).AsConfig . )}}
{{- end }}